name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Droplet
      env:
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        POSTGRES_CONNECTION_STRING: ${{ secrets.POSTGRES_CONNECTION_STRING }}
      run: |
        set -e
        ssh -o StrictHostKeyChecking=no root@159.203.176.36 << 'EOF'
          echo "Updating APP_PASSWORD environment variable"
          sudo sed -i '/^APP_PASSWORD=/d' /etc/environment
          echo "APP_PASSWORD=${APP_PASSWORD}" | sudo tee -a /etc/environment
          
          echo "Updating OPENAI_API_KEY environment variable"
          sudo sed -i '/^OPENAI_API_KEY=/d' /etc/environment
          echo "OPENAI_API_KEY=${OPENAI_API_KEY}" | sudo tee -a /etc/environment
          
          echo "Updating POSTGRES_CONNECTION_STRING environment variable"
          sudo sed -i '/^POSTGRES_CONNECTION_STRING=/d' /etc/environment
          echo "POSTGRES_CONNECTION_STRING=${POSTGRES_CONNECTION_STRING}" | sudo tee -a /etc/environment

          cd /root/keenai
          git fetch origin
          git reset --hard origin/main
          source /root/keenai/.venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl daemon-reload
          sudo systemctl restart streamlit
        EOF
