name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Droplet
      env:
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
      run: |
        set -e
        ssh -o StrictHostKeyChecking=no root@159.203.176.36 << 'EOF'
          echo "Setting APP_PASSWORD environment variable"
          echo "APP_PASSWORD=${APP_PASSWORD}" | sudo tee /etc/environment
          echo "APP_PASSWORD is set to: $APP_PASSWORD"
          cd /root/keenai
          git fetch origin
          git reset --hard origin/main
          sudo systemctl daemon-reload
          sudo systemctl restart streamlit
        EOF